CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS user_info (
  user_id BIGSERIAL PRIMARY KEY REFERENCES users(id),
  password TEXT NOT NULL,
  avatar TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  value VARCHAR(60) PRIMARY KEY,
  user_id BIGSERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expire_date TIMESTAMP WITH TIMEZONE NOT NULL
);
