CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS users_info (
  user_id BIGSERIAL PRIMARY KEY REFERENCES users(id),
  password VARCHAR(128) NOT NULL,
  avatar VARCHAR(64) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  value VARCHAR(60) PRIMARY KEY,
  user_id BIGSERIAL REFERENCES users(id) ON DELETE CASCADE,
  expire_date TIMESTAMP WITH TIME ZONE NOT NULL
);
